AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Snow Forecast API deployed on AWS Lambda'

Globals:
  Function:
    Timeout: 300  # 5 minutes for web scraping
    MemorySize: 1024
    Runtime: python3.12

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

Resources:
  SnowForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Timeout: 300
      MemorySize: 2048  # Increased for Playwright
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          PLAYWRIGHT_BROWSERS_PATH: /tmp
          PYTHONPATH: /var/task:/var/task/src
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
      Layers:
        - !Ref PlaywrightLayer

  PlaywrightLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: playwright-layer
      Description: Playwright browser binaries for Lambda
      ContentUri: layers/playwright/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref SnowForecastFunction